In [1]:
import os
import json
import pandas as pd

#AGGREGATED TRANSACTION  

path=r"C:\Users\craj1\OneDrive\Documents\DS_Projects\pulse\data\aggregated\transaction\country\india\state"
Agg_state_list=os.listdir(path)
Agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [2]:
clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'Transaction_type': [],
    'Transaction_count': [],
    'Transaction_amount': []
}

for state in Agg_state_list:
    state_path = os.path.join(path, state)
    years = os.listdir(state_path)
    
    for year in years:
        year_path = os.path.join(state_path, year)
        files = os.listdir(year_path)
        
        for file in files:
            file_path = os.path.join(year_path, file)
            
            with open(file_path, 'r') as f:
                data = json.load(f)

                for i in data['data']['transactionData']:
                        name = i['name']
                        count = i['paymentInstruments'][0]['count']
                        amount = i['paymentInstruments'][0]['amount']
                        
                        clm['State'].append(state)
                        clm['Year'].append(year)
                        clm['Quarter'].append(int(file.replace('.json', '')))
                        clm['Transaction_type'].append(name)
                        clm['Transaction_count'].append(count)
                        clm['Transaction_amount'].append(amount)

Agg_Trans = pd.DataFrame(clm)

In [3]:
Agg_Trans.sample(11)

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
3387,nagaland,2019,3,Financial Services,210,2.293198e+05
1366,goa,2023,2,Peer-to-peer payments,8589659,2.698528e+10
4644,uttar-pradesh,2019,3,Peer-to-peer payments,26990786,9.513402e+10
590,bihar,2019,3,Peer-to-peer payments,15446119,6.183178e+10
2949,manipur,2018,4,Recharge & bill payments,113507,1.889806e+07
3158,meghalaya,2022,1,Others,6218,5.116238e+06
761,chandigarh,2021,1,Peer-to-peer payments,1472084,5.916467e+09
1991,jharkhand,2019,3,Merchant payments,4766457,1.494546e+09
4411,telangana,2021,4,Recharge & bill payments,66477036,4.476040e+10
4689,uttar-pradesh,2021,4,Merchant payments,183966052,1.428893e+11
3390,nagaland,2019,4,Peer-to-peer payments,128674,7.772986e+08

In [4]:
#AGGREGATED USER
path1=r"C:\Users\craj1\OneDrive\Documents\DS_Projects\pulse\data\aggregated\user\country\india\state"
Agg_state_list=os.listdir(path1)
Agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [5]:
clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'registeredUsers': [],
    'appOpens': [],
    'User_brand': [],
    'User_count': [],
    'User_percentage': [],
}

for state in Agg_state_list:
    state_path = os.path.join(path1, state)
    years = os.listdir(state_path)
    
    for year in years:
        year_path = os.path.join(state_path, year)
        files = os.listdir(year_path)
        
        for file in files:
            file_path = os.path.join(year_path, file)
            
            with open(file_path, 'r') as f:
                data = json.load(f)

            if data.get('data'):

                registeredUsers = data['data']['aggregated'].get('registeredUsers')
                appOpens = data['data']['aggregated'].get('appOpens')

                users_device = data['data'].get('usersByDevice')
    
                if users_device:   # This prevents NoneType error

                    for i in users_device:
                        brand = i['brand']
                        count = i['count']
                        percentage = i['percentage']
                        
                        clm['State'].append(state)
                        clm['Year'].append(year)
                        clm['Quarter'].append(int(file.replace('.json', '')))
                        clm['registeredUsers'].append(registeredUsers)
                        clm['appOpens'].append(appOpens)
                        clm['User_brand'].append(brand)
                        clm['User_count'].append(count)
                        clm['User_percentage'].append(percentage)


Agg_User = pd.DataFrame(clm)

In [6]:
Agg_User.head()

,State,Year,Quarter,registeredUsers,appOpens,User_brand,User_count,User_percentage
0,andaman-&-nicobar-islands,2018,1,6740,0,Xiaomi,1665,0.247033
1,andaman-&-nicobar-islands,2018,1,6740,0,Samsung,1445,0.214392
2,andaman-&-nicobar-islands,2018,1,6740,0,Vivo,982,0.145697
3,andaman-&-nicobar-islands,2018,1,6740,0,Oppo,501,0.074332
4,andaman-&-nicobar-islands,2018,1,6740,0,OnePlus,332,0.049258

In [7]:
#AGGREGATED INSURANCE
path3=r"C:\Users\craj1\OneDrive\Documents\DS_Projects\pulse\data\aggregated\insurance\country\india\state"
Agg_state_list=os.listdir(path3)
Agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [8]:
clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'Insurance_type': [],
    'Insurance_count': [],
    'Insurance_amount': []
}

for state in Agg_state_list:
    state_path = os.path.join(path3, state)
    years = os.listdir(state_path)
    
    for year in years:
        year_path = os.path.join(state_path, year)
        files = os.listdir(year_path)
        
        for file in files:
            file_path = os.path.join(year_path, file)
            
            with open(file_path, 'r') as f:
                data = json.load(f)

                for i in data['data']['transactionData']:
                        name = i['name']
                        count = i['paymentInstruments'][0]['count']
                        amount = i['paymentInstruments'][0]['amount']
                        
                        clm['State'].append(state)
                        clm['Year'].append(year)
                        clm['Quarter'].append(int(file.strip('.json')))
                        clm['Insurance_type'].append(name)
                        clm['Insurance_count'].append(count)
                        clm['Insurance_amount'].append(amount)

Agg_Insur = pd.DataFrame(clm)

In [9]:
Agg_Insur.head()

,State,Year,Quarter,Insurance_type,Insurance_count,Insurance_amount
0,andaman-&-nicobar-islands,2020,2,Insurance,6,1360.0
1,andaman-&-nicobar-islands,2020,3,Insurance,41,15380.0
2,andaman-&-nicobar-islands,2020,4,Insurance,124,157975.0
3,andaman-&-nicobar-islands,2021,1,Insurance,225,244266.0
4,andaman-&-nicobar-islands,2021,2,Insurance,137,181504.0

In [10]:
#MAP TRANSACTION
path4=r"C:\Users\craj1\OneDrive\Documents\DS_Projects\pulse\data\map\transaction\hover\country\india\state"
Agg_state_list=os.listdir(path4)
Agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [80]:
clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'District': [],
    'Transaction_count': [],
    'Transaction_amount': []
}

for state in Agg_state_list:
    state_path = os.path.join(path4, state)
    years = os.listdir(state_path)
    
    for year in years:
        year_path = os.path.join(state_path, year)
        files = os.listdir(year_path)
        
        for file in files:
            file_path = os.path.join(year_path, file)
            
            with open(file_path, 'r') as f:
                data = json.load(f)

                for i in data['data']['hoverDataList']:
                        name = i['name']
                        count = i['metric'][0]['count']
                        amount = i['metric'][0]['amount']
                        
                        clm['State'].append(state)
                        clm['Year'].append(year)
                        clm['Quarter'].append(int(file.replace('.json', '')))
                        clm['District'].append(name)
                        clm['Transaction_count'].append(count)
                        clm['Transaction_amount'].append(amount)

Map_Trans = pd.DataFrame(clm)

In [83]:
Map_Trans.head()

,State,Year,Quarter,District,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman district,9395,2.394824e+07

In [13]:
#MAP USER
path5=r"C:\Users\craj1\OneDrive\Documents\DS_Projects\pulse\data\map\user\hover\country\india\state"
Agg_state_list=os.listdir(path5)
Agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [84]:
import os
import json
import pandas as pd

clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'District': [],
    'Registered_Users': [],
    'App_Opens': []
}

for state in Agg_state_list:
    
    state_path = os.path.join(path5, state)
    years = os.listdir(state_path)
    
    for year in years:
        
        year_path = os.path.join(state_path, year)
        files = os.listdir(year_path)
        
        for file in files:
            
            file_path = os.path.join(year_path, file)
            
            with open(file_path, 'r') as f:
                data = json.load(f)
            
            # 🔹 Check if hoverData exists
            if data.get('data') and data['data'].get('hoverData'):
                
                hover_data = data['data']['hoverData']
                
                for district in hover_data:
                    
                    registeredUsers = hover_data[district]['registeredUsers']
                    appOpens = hover_data[district]['appOpens']
                    
                    clm['State'].append(state)
                    clm['Year'].append(year)
                    clm['Quarter'].append(int(file.replace('.json', '')))
                    clm['District'].append(district)
                    clm['Registered_Users'].append(registeredUsers)
                    clm['App_Opens'].append(appOpens)

Map_user = pd.DataFrame(clm)

In [85]:
Map_user.head()

,State,Year,Quarter,District,Registered_Users,App_Opens
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars district,262,0
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911,0
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143,0

In [16]:
#MAP INSURANCE
path6=r"C:\Users\craj1\OneDrive\Documents\DS_Projects\pulse\data\map\insurance\hover\country\india\state"
Agg_state_list=os.listdir(path6)
Agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [87]:
clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'District': [],
    'Insurance_count': [],
    'Insurance_amount': []
}

for state in Agg_state_list:
    state_path = os.path.join(path6, state)
    years = os.listdir(state_path)
    
    for year in years:
        year_path = os.path.join(state_path, year)
        files = os.listdir(year_path)
        
        for file in files:
            file_path = os.path.join(year_path, file)
            
            with open(file_path, 'r') as f:
                data = json.load(f)

                if data.get('data') and data['data'].get('hoverDataList'):

                    for i in data['data']['hoverDataList']:
                            name = i['name']
                            count = i['metric'][0]['count']
                            amount = i['metric'][0]['amount']
                            
                            clm['State'].append(state)
                            clm['Year'].append(year)
                            clm['Quarter'].append(int(file.strip('.json')))
                            clm['District'].append(name)
                            clm['Insurance_count'].append(count)
                            clm['Insurance_amount'].append(amount)

Map_Insur = pd.DataFrame(clm)

In [88]:
Map_Insur.head()

,State,Year,Quarter,District,Insurance_count,Insurance_amount
0,andaman-&-nicobar-islands,2020,2,south andaman district,3,795.0
1,andaman-&-nicobar-islands,2020,2,nicobars district,3,565.0
2,andaman-&-nicobar-islands,2020,3,north and middle andaman district,1,281.0
3,andaman-&-nicobar-islands,2020,3,south andaman district,35,13651.0
4,andaman-&-nicobar-islands,2020,3,nicobars district,5,1448.0

In [19]:
#TOP TRANSACTION 
path7=r"C:\Users\craj1\OneDrive\Documents\DS_Projects\pulse\data\top\transaction\country\india\state"
Agg_state_list=os.listdir(path7)
Agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [20]:
clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'Level': [],
    'Entity_name': [],
    'Transaction_count': [],
    'Transaction_amount': []
}

for state in Agg_state_list:
    state_path = os.path.join(path7, state)
    years = os.listdir(state_path)
    
    for year in years:
        year_path = os.path.join(state_path, year)
        files = os.listdir(year_path)
        
        for file in files:
            file_path = os.path.join(year_path, file)
            
            with open(file_path, 'r') as f:
                data = json.load(f)
                
                #STATES
                if data['data'].get('states'):
                    for i in data['data']['states']:
                        clm['State'].append(state)
                        clm['Year'].append(year)
                        clm['Quarter'].append(int(file.replace('.json', '')))
                        clm['Level'].append('State')
                        clm['Entity_name'].append(i['entityName'])
                        clm['Transaction_count'].append(i['metric']['count'])
                        clm['Transaction_amount'].append(i['metric']['amount'])
                
                #DISTRICTS
                if data['data'].get('districts'):
                    for i in data['data']['districts']:
                        clm['State'].append(state)
                        clm['Year'].append(year)
                        clm['Quarter'].append(int(file.replace('.json', '')))
                        clm['Level'].append('District')
                        clm['Entity_name'].append(i['entityName'])
                        clm['Transaction_count'].append(i['metric']['count'])
                        clm['Transaction_amount'].append(i['metric']['amount'])
                
                #PINCODES
                if data['data'].get('pincodes'):
                    for i in data['data']['pincodes']:
                        clm['State'].append(state)
                        clm['Year'].append(year)
                        clm['Quarter'].append(int(file.replace('.json', '')))
                        clm['Level'].append('Pincode')
                        clm['Entity_name'].append(i['entityName'])
                        clm['Transaction_count'].append(i['metric']['count'])
                        clm['Transaction_amount'].append(i['metric']['amount'])

Top_Trans = pd.DataFrame(clm)

In [21]:
Top_Trans.head()

,State,Year,Quarter,Level,Entity_name,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,District,south andaman,5688,1.256025e+07
1,andaman-&-nicobar-islands,2018,1,District,nicobars,528,1.139849e+06
2,andaman-&-nicobar-islands,2018,1,District,north and middle andaman,442,9.316631e+05
3,andaman-&-nicobar-islands,2018,1,Pincode,744101,1622,2.769298e+06
4,andaman-&-nicobar-islands,2018,1,Pincode,744103,1223,2.238042e+06

In [22]:
#TOP USER 
path8=r"C:\Users\craj1\OneDrive\Documents\DS_Projects\pulse\data\top\user\country\india\state"
Agg_state_list=os.listdir(path8)
Agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [93]:
clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'Level': [],
    'Entity_name': [],
    'Registered_Users': [],
}

for state in Agg_state_list:
    state_path = os.path.join(path8, state)
    years = os.listdir(state_path)
    
    for year in years:
        year_path = os.path.join(state_path, year)
        files = os.listdir(year_path)
        
        for file in files:
            file_path = os.path.join(year_path, file)
            
            with open(file_path, 'r') as f:
                data = json.load(f)
                
                #STATES
                if data['data'].get('states'):
                    for i in data['data']['states']:
                        clm['State'].append(state)
                        clm['Year'].append(year)
                        clm['Quarter'].append(int(file.replace('.json', '')))
                        clm['Level'].append('State')
                        clm['Entity_name'].append(i['name'])
                        clm['Registered_Users'].append(i['registeredUsers'])
                
                #DISTRICTS
                if data['data'].get('districts'):
                    for i in data['data']['districts']:
                        clm['State'].append(state)
                        clm['Year'].append(year)
                        clm['Quarter'].append(int(file.replace('.json', '')))
                        clm['Level'].append('District')
                        clm['Entity_name'].append(i['name'])
                        clm['Registered_Users'].append(i['registeredUsers'])
                
                #PINCODES
                if data['data'].get('pincodes'):
                    for i in data['data']['pincodes']:
                        clm['State'].append(state)
                        clm['Year'].append(year)
                        clm['Quarter'].append(int(file.replace('.json', '')))
                        clm['Level'].append('Pincode')
                        clm['Entity_name'].append(i['name'])
                        clm['Registered_Users'].append(i['registeredUsers'])

Top_User = pd.DataFrame(clm)

In [94]:
Top_User.head()

,State,Year,Quarter,Level,Entity_name,Registered_Users
0,andaman-&-nicobar-islands,2018,1,District,south andaman,5846
1,andaman-&-nicobar-islands,2018,1,District,north and middle andaman,632
2,andaman-&-nicobar-islands,2018,1,District,nicobars,262
3,andaman-&-nicobar-islands,2018,1,Pincode,744103,1608
4,andaman-&-nicobar-islands,2018,1,Pincode,744101,1108

In [25]:
#TOP INSURANCE
path9=r"C:\Users\craj1\OneDrive\Documents\DS_Projects\pulse\data\top\insurance\country\india\state"
Agg_state_list=os.listdir(path9)
Agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [97]:
clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'Level': [],
    'Entity_name': [],
    'Insurance_count': [],
    'Insurance_amount': []
}

for state in Agg_state_list:
    state_path = os.path.join(path9, state)
    years = os.listdir(state_path)
    
    for year in years:
        year_path = os.path.join(state_path, year)
        files = os.listdir(year_path)
        
        for file in files:
            file_path = os.path.join(year_path, file)
            
            with open(file_path, 'r') as f:
                data = json.load(f)
                
                #STATES
                if data['data'].get('states'):
                    for i in data['data']['states']:
                        clm['State'].append(state)
                        clm['Year'].append(year)
                        clm['Quarter'].append(int(file.replace('.json', '')))
                        clm['Level'].append('State')
                        clm['Entity_name'].append(i['entityName'])
                        clm['Insurance_count'].append(i['metric']['count'])
                        clm['Insurance_amount'].append(i['metric']['amount'])
                
                #DISTRICTS
                if data['data'].get('districts'):
                    for i in data['data']['districts']:
                        clm['State'].append(state)
                        clm['Year'].append(year)
                        clm['Quarter'].append(int(file.replace('.json', '')))
                        clm['Level'].append('District')
                        clm['Entity_name'].append(i['entityName'])
                        clm['Insurance_count'].append(i['metric']['count'])
                        clm['Insurance_amount'].append(i['metric']['amount'])
                
                #PINCODES
                if data['data'].get('pincodes'):
                    for i in data['data']['pincodes']:
                        clm['State'].append(state)
                        clm['Year'].append(year)
                        clm['Quarter'].append(int(file.replace('.json', '')))
                        clm['Level'].append('Pincode')
                        clm['Entity_name'].append(i['entityName'])
                        clm['Insurance_count'].append(i['metric']['count'])
                        clm['Insurance_amount'].append(i['metric']['amount'])

Top_Insur = pd.DataFrame(clm)

In [98]:
Top_Insur.head()

,State,Year,Quarter,Level,Entity_name,Insurance_count,Insurance_amount
0,andaman-&-nicobar-islands,2020,2,District,nicobars,3,565.0
1,andaman-&-nicobar-islands,2020,2,District,south andaman,3,795.0
2,andaman-&-nicobar-islands,2020,2,Pincode,744301,3,565.0
3,andaman-&-nicobar-islands,2020,2,Pincode,744104,2,513.0
4,andaman-&-nicobar-islands,2020,2,Pincode,744101,1,282.0

In [28]:
#AGGREGATED TRANSACTION
print(Agg_Trans.shape)

(5034, 6)

In [29]:
print(Agg_Trans.dtypes)

State                  object
Year                   object
Quarter                 int64
Transaction_type       object
Transaction_count       int64
Transaction_amount    float64
dtype: object

In [30]:
print(Agg_Trans.isnull().sum())

State                 0
Year                  0
Quarter               0
Transaction_type      0
Transaction_count     0
Transaction_amount    0
dtype: int64

In [31]:
print(Agg_Trans.duplicated().sum())

0

In [32]:
Agg_Trans['Year'] = Agg_Trans['Year'].astype(int)

In [33]:
print(Agg_Trans.dtypes)

State                  object
Year                    int64
Quarter                 int64
Transaction_type       object
Transaction_count       int64
Transaction_amount    float64
dtype: object

In [34]:
#AGGREGATED USER
print(Agg_User.shape)

(6732, 8)

In [35]:
print(Agg_User.dtypes)

State               object
Year                object
Quarter              int64
registeredUsers      int64
appOpens             int64
User_brand          object
User_count           int64
User_percentage    float64
dtype: object

In [36]:
Agg_User['Year'] = Agg_User['Year'].astype(int)

In [37]:
print(Agg_User.dtypes)

State               object
Year                 int64
Quarter              int64
registeredUsers      int64
appOpens             int64
User_brand          object
User_count           int64
User_percentage    float64
dtype: object

In [38]:
print(Agg_User.isnull().sum())

State              0
Year               0
Quarter            0
registeredUsers    0
appOpens           0
User_brand         0
User_count         0
User_percentage    0
dtype: int64

In [39]:
print(Agg_User.duplicated().sum())

0

In [40]:
#AGGREGATED INSURANCE
print(Agg_Insur.shape)

(682, 6)

In [41]:
print(Agg_Insur.dtypes)

State                object
Year                 object
Quarter               int64
Insurance_type       object
Insurance_count       int64
Insurance_amount    float64
dtype: object

In [43]:
Agg_Insur['Year'] = Agg_Insur['Year'].astype(int)

In [44]:
print(Agg_Insur.dtypes)

State                object
Year                  int64
Quarter               int64
Insurance_type       object
Insurance_count       int64
Insurance_amount    float64
dtype: object

In [45]:
print(Agg_Insur.isnull().sum())

State               0
Year                0
Quarter             0
Insurance_type      0
Insurance_count     0
Insurance_amount    0
dtype: int64

In [46]:
print(Agg_Insur.duplicated().sum())

0

In [47]:
#MAP TRANSACTION
print(Map_Trans.shape)
print(Map_Trans.dtypes)
print(Map_Trans.isnull().sum())
print(Map_Trans.duplicated().sum())

(20604, 6)
State                  object
Year                   object
Quarter                 int64
Transaction_type       object
Transaction_count       int64
Transaction_amount    float64
dtype: object
State                 0
Year                  0
Quarter               0
Transaction_type      0
Transaction_count     0
Transaction_amount    0
dtype: int64
0

In [48]:
Map_Trans['Year'] = Map_Trans['Year'].astype(int)

In [49]:
print(Map_Trans.dtypes)

State                  object
Year                    int64
Quarter                 int64
Transaction_type       object
Transaction_count       int64
Transaction_amount    float64
dtype: object

In [50]:
#MAP USER
print(Map_user.shape)
print(Map_user.dtypes)
print(Map_user.isnull().sum())
print(Map_user.duplicated().sum())

(20608, 6)
State              object
Year               object
Quarter             int64
District           object
registeredUsers     int64
appOpens            int64
dtype: object
State              0
Year               0
Quarter            0
District           0
registeredUsers    0
appOpens           0
dtype: int64
0

In [51]:
Map_user['Year'] = Map_user['Year'].astype(int)

In [52]:
print(Map_user.dtypes)

State              object
Year                int64
Quarter             int64
District           object
registeredUsers     int64
appOpens            int64
dtype: object

In [53]:
#MAP INSURANCE
print(Map_Insur.shape)
print(Map_Insur.dtypes)
print(Map_Insur.isnull().sum())
print(Map_Insur.duplicated().sum())

(13876, 6)
State                object
Year                 object
Quarter               int64
Insurance_type       object
Insurance_count       int64
Insurance_amount    float64
dtype: object
State               0
Year                0
Quarter             0
Insurance_type      0
Insurance_count     0
Insurance_amount    0
dtype: int64
0

In [54]:
Map_Insur['Year'] = Map_Insur['Year'].astype(int)

In [55]:
print(Map_Insur.dtypes)

State                object
Year                  int64
Quarter               int64
Insurance_type       object
Insurance_count       int64
Insurance_amount    float64
dtype: object

In [56]:
#TOP TRANSACTION
print(Top_Trans.shape)
print(Top_Trans.dtypes)
print(Top_Trans.isnull().sum())
print(Top_Trans.duplicated().sum())

(18295, 7)
State                  object
Year                   object
Quarter                 int64
Level                  object
Entity_name            object
Transaction_count       int64
Transaction_amount    float64
dtype: object
State                 0
Year                  0
Quarter               0
Level                 0
Entity_name           2
Transaction_count     0
Transaction_amount    0
dtype: int64
0

In [57]:
Top_Trans[Top_Trans['Entity_name'].isnull()]

,State,Year,Quarter,Level,Entity_name,Transaction_count,Transaction_amount
8718,ladakh,2019,4,Pincode,None,2014,1.009866e+07
8768,ladakh,2020,4,Pincode,None,13717,3.671160e+07

In [58]:
Top_Trans['Entity_name'] = Top_Trans['Entity_name'].fillna('Unknown_Pincode')

In [59]:
Top_Trans[Top_Trans['Entity_name'].isnull()]

Empty DataFrame
Columns: [State, Year, Quarter, Level, Entity_name, Transaction_count, Transaction_amount]
Index: []

In [60]:
print(Top_Trans.isnull().sum())

State                 0
Year                  0
Quarter               0
Level                 0
Entity_name           0
Transaction_count     0
Transaction_amount    0
dtype: int64

In [61]:
Top_Trans['Year'] = Top_Trans['Year'].astype(int)

In [62]:
print(Top_Trans.dtypes)

State                  object
Year                    int64
Quarter                 int64
Level                  object
Entity_name            object
Transaction_count       int64
Transaction_amount    float64
dtype: object

In [63]:
#TOP User
print(Top_User.shape)
print(Top_User.dtypes)
print(Top_User.isnull().sum())
print(Top_User.duplicated().sum())

(18296, 6)
State              object
Year               object
Quarter             int64
Level              object
Name               object
registeredUsers     int64
dtype: object
State              0
Year               0
Quarter            0
Level              0
Name               0
registeredUsers    0
dtype: int64
0

In [64]:
Top_User['Year'] = Top_User['Year'].astype(int)

In [65]:
print(Top_User.dtypes)

State              object
Year                int64
Quarter             int64
Level              object
Name               object
registeredUsers     int64
dtype: object

In [66]:
#TOP Insur
print(Top_Insur.shape)
print(Top_Insur.dtypes)
print(Top_Insur.isnull().sum())
print(Top_Insur.duplicated().sum())

(12276, 7)
State                  object
Year                   object
Quarter                 int64
Level                  object
Entity_name            object
Transaction_count       int64
Transaction_amount    float64
dtype: object
State                 0
Year                  0
Quarter               0
Level                 0
Entity_name           3
Transaction_count     0
Transaction_amount    0
dtype: int64
0

In [67]:
Top_Insur['Year'] = Top_Insur['Year'].astype(int)

In [68]:
print(Top_Insur.dtypes)

State                  object
Year                    int64
Quarter                 int64
Level                  object
Entity_name            object
Transaction_count       int64
Transaction_amount    float64
dtype: object

In [69]:
Top_Insur[Top_Insur['Entity_name'].isnull()]

,State,Year,Quarter,Level,Entity_name,Transaction_count,Transaction_amount
5844,ladakh,2020,3,Pincode,None,1,281.0
5854,ladakh,2020,4,Pincode,None,1,658.0
5947,ladakh,2022,4,Pincode,None,8,16020.0

In [70]:
Top_Insur['Entity_name'] = Top_Insur['Entity_name'].fillna('Unknown_Pincode')

In [71]:
Top_Insur[Top_Insur['Entity_name'].isnull()]

Empty DataFrame
Columns: [State, Year, Quarter, Level, Entity_name, Transaction_count, Transaction_amount]
Index: []

In [72]:
Top_Insur[Top_Insur['Transaction_amount'] == 281.0]

,State,Year,Quarter,Level,Entity_name,Transaction_count,Transaction_amount
7,andaman-&-nicobar-islands,2020,3,District,north and middle andaman,1,281.0
5841,ladakh,2020,3,Pincode,194105,1,281.0
5844,ladakh,2020,3,Pincode,Unknown_Pincode,1,281.0

In [73]:
#Connecting my mysql and Jupyter Notebook
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="root",
)

cursor = conn.cursor()

In [137]:
database_name = "phonepe_pulse"
cursor.execute(f"CREATE DATABASE {database_name}")

In [140]:
cursor.execute("USE phonepe_pulse;")

In [141]:
cursor.execute("""
CREATE TABLE Aggregated_Transaction (
    State VARCHAR(100),
    Year INT,
    Quarter INT,
    Transaction_type VARCHAR(100),
    Transaction_count INT,
    Transaction_amount Float
);
""")

In [142]:
cursor.execute("""
CREATE TABLE Aggregated_User (
    State VARCHAR(100),
    Year INT,
    Quarter INT,
    RegisteredUsers INT,
    AppOpens INT,
    Brand VARCHAR(100),
    User_count INT,
    Percentage Float
);
""")

In [143]:
cursor.execute("""
CREATE TABLE Aggregated_Insurance (
    State VARCHAR(100),
    Year INT,
    Quarter INT,
    Insurance_type VARCHAR(100),
    Insurance_count INT,
    Insurance_amount Float
);
""")

In [144]:
cursor.execute("""
CREATE TABLE Map_Transaction (
    State VARCHAR(100),
    Year INT,
    Quarter INT,
    District VARCHAR(150),
    Transaction_count INT,
    Transaction_amount Float
);
""")

In [145]:
cursor.execute("""
CREATE TABLE Map_User (
    State VARCHAR(100),
    Year INT,
    Quarter INT,
    District VARCHAR(150),
    Registered_users INT,
    App_opens INT
);
""")

In [146]:
cursor.execute("""
CREATE TABLE Map_Insurance (
    State VARCHAR(100),
    Year INT,
    Quarter INT,
    District VARCHAR(150),
    Insurance_count INT,
    Insurance_amount Float
);
""")

In [147]:
cursor.execute("""
CREATE TABLE Top_Transaction (
    State VARCHAR(100),
    Year INT,
    Quarter INT,
    Level VARCHAR(50),
    Entity_name VARCHAR(150),
    Transaction_count INT,
    Transaction_amount Float
);
""")

In [148]:
cursor.execute("""
CREATE TABLE Top_User (
    State VARCHAR(100),
    Year INT,
    Quarter INT,
    Level VARCHAR(50),
    Entity_name VARCHAR(150),
    Registered_users INT
);
""")

In [149]:
cursor.execute("""
CREATE TABLE Top_Insurance (
    State VARCHAR(100),
    Year INT,
    Quarter INT,
    Level VARCHAR(50),
    Entity_name VARCHAR(150),
    Insurance_count INT,
    Insurance_amount Float
);
""")

In [150]:
conn.commit()

In [151]:
cursor.close()
conn.close()

In [143]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:root@localhost/phonepe_pulse")

In [76]:
Agg_Trans.to_sql('Aggregated_Transaction', engine, if_exists='append', index=False)

C:\Users\craj1\AppData\Local\Temp\ipykernel_18828\4183251842.py:1: UserWarning: The provided table name 'Aggregated_Transaction' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Agg_Trans.to_sql('Aggregated_Transaction', engine, if_exists='append', index=False)

5034

In [77]:
pd.read_sql("SELECT COUNT(*) FROM aggregated_transaction;", engine)

   COUNT(*)
0      5034

In [76]:
Agg_User.to_sql('aggregated_user', engine, if_exists='append', index=False)

6732

In [77]:
Agg_Insur.to_sql('aggregated_Insurance', engine, if_exists='append', index=False)

C:\Users\craj1\AppData\Local\Temp\ipykernel_19736\4157789155.py:1: UserWarning: The provided table name 'aggregated_Insurance' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Agg_Insur.to_sql('aggregated_Insurance', engine, if_exists='append', index=False)

682

In [82]:
Map_Trans.to_sql('Map_Transaction', engine, if_exists='append', index=False)

C:\Users\craj1\AppData\Local\Temp\ipykernel_19736\536760425.py:1: UserWarning: The provided table name 'Map_Transaction' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Map_Trans.to_sql('Map_Transaction', engine, if_exists='append', index=False)

20604

In [86]:
Map_user.to_sql('map_user', engine, if_exists='append', index=False)

20608

In [89]:
Map_Insur.to_sql('map_insurance', engine, if_exists='append', index=False)

13876

In [90]:
Top_Trans.to_sql('top_transaction', engine, if_exists='append', index=False)

18295

In [95]:
Top_User.to_sql('top_user', engine, if_exists='append', index=False)

18296

In [99]:
Top_Insur.to_sql('top_insurance', engine, if_exists='append', index=False)

12276

In [100]:
#Transaction Analysis for Market Expansion
#Scenario
#PhonePe operates in a highly competitive market, and understanding transaction dynamics at the state level is crucial for strategic decision-making. With a growing number of transactions across different regions, the company seeks to analyze its transaction data to identify trends, opportunities, and potential areas for expansion.

In [117]:
# Query 1 — Total Transaction Value by State
#Which states contribute most to transaction revenue?

In [102]:
query1 = """
SELECT State,
       SUM(Transaction_amount) AS Total_Transaction_Value
FROM aggregated_transaction
GROUP BY State
ORDER BY Total_Transaction_Value DESC;
"""

In [104]:
result1 = pd.read_sql(query1, engine)

result1

                                 State  Total_Transaction_Value
0                            telangana             4.165596e+13
1                            karnataka             4.067872e+13
2                          maharashtra             4.037420e+13
3                       andhra-pradesh             3.466908e+13
4                        uttar-pradesh             2.688521e+13
5                            rajasthan             2.634324e+13
6                       madhya-pradesh             1.912528e+13
7                                bihar             1.790135e+13
8                          west-bengal             1.558416e+13
9                               odisha             1.226398e+13
10                          tamil-nadu             1.193622e+13
11                               delhi             1.163752e+13
12                             gujarat             1.019291e+13
13                             haryana             9.645037e+12
14                           jharkhand             5.906646e+12
15                        chhattisgarh             4.890472e+12
16                               assam             3.460792e+12
17                              kerala             3.076269e+12
18                              punjab             2.983078e+12
19                         uttarakhand             1.916489e+12
20                     jammu-&-kashmir             1.184683e+12
21                    himachal-pradesh             6.875374e+11
22                                 goa             5.110212e+11
23                          chandigarh             2.929066e+11
24                   arunachal-pradesh             2.744350e+11
25                          puducherry             2.373171e+11
26  dadra-&-nagar-haveli-&-daman-&-diu             2.017199e+11
27                             tripura             2.005834e+11
28                             manipur             1.862656e+11
29                           meghalaya             1.625439e+11
30                            nagaland             1.303586e+11
31                              sikkim             1.189454e+11
32                              ladakh             8.899462e+10
33           andaman-&-nicobar-islands             7.066745e+10
34                             mizoram             4.610210e+10
35                         lakshadweep             1.609321e+09

In [118]:
#Query 2 — Total Transaction Count by State
#Which states have highest transaction volume?

In [106]:
query2 = """
SELECT State,
       SUM(Transaction_count) AS Total_Transaction_Count
FROM aggregated_transaction
GROUP BY State
ORDER BY Total_Transaction_Count DESC;
"""

In [107]:
result2 = pd.read_sql(query2, engine)

result2

                                 State  Total_Transaction_Count
0                          maharashtra             3.198521e+10
1                            karnataka             3.097095e+10
2                            telangana             2.617468e+10
3                       andhra-pradesh             1.891870e+10
4                        uttar-pradesh             1.852360e+10
5                            rajasthan             1.710854e+10
6                       madhya-pradesh             1.407218e+10
7                                bihar             1.094103e+10
8                          west-bengal             9.191500e+09
9                               odisha             8.918527e+09
10                               delhi             8.495317e+09
11                          tamil-nadu             7.796386e+09
12                             haryana             6.744901e+09
13                             gujarat             6.726865e+09
14                           jharkhand             4.266421e+09
15                        chhattisgarh             3.733644e+09
16                              kerala             2.300898e+09
17                               assam             2.262441e+09
18                              punjab             1.772412e+09
19                         uttarakhand             1.458837e+09
20                     jammu-&-kashmir             8.206027e+08
21                    himachal-pradesh             5.008106e+08
22                                 goa             3.649444e+08
23                          chandigarh             2.038553e+08
24  dadra-&-nagar-haveli-&-daman-&-diu             2.012184e+08
25                          puducherry             1.666053e+08
26                   arunachal-pradesh             1.602234e+08
27                             tripura             1.208385e+08
28                           meghalaya             8.863542e+07
29                             manipur             7.335034e+07
30                              sikkim             6.586084e+07
31                            nagaland             5.476874e+07
32           andaman-&-nicobar-islands             3.970695e+07
33                              ladakh             3.934588e+07
34                             mizoram             1.953575e+07
35                         lakshadweep             8.839940e+05

In [119]:
#Query 3 — Year-wise Transaction Growth by State
#How transactions are growing across states?

In [109]:
query3 = """
SELECT State,
       Year,
       SUM(Transaction_amount) AS Yearly_Transaction_Value
FROM aggregated_transaction
GROUP BY State, Year
ORDER BY State, Year;
"""

In [110]:
result3 = pd.read_sql(query3, engine)

result3

                         State  Year  Yearly_Transaction_Value
0    andaman-&-nicobar-islands  2018              1.890761e+08
1    andaman-&-nicobar-islands  2019              4.734648e+08
2    andaman-&-nicobar-islands  2020              1.296423e+09
3    andaman-&-nicobar-islands  2021              4.925488e+09
4    andaman-&-nicobar-islands  2022              1.211026e+10
..                         ...   ...                       ...
247                west-bengal  2020              5.527316e+11
248                west-bengal  2021              1.347047e+12
249                west-bengal  2022              2.692527e+12
250                west-bengal  2023              4.227142e+12
251                west-bengal  2024              6.387113e+12

[252 rows x 3 columns]

In [111]:
#Query 4 — Quarterly Trend Across India
#what is Quarterly Transaction?

In [112]:
query4 = """
SELECT Year,
       Quarter,
       SUM(Transaction_amount) AS Quarterly_Total
FROM aggregated_transaction
GROUP BY Year, Quarter
ORDER BY Year, Quarter;
"""

In [113]:
result4 = pd.read_sql(query4, engine)

result4

    Year  Quarter  Quarterly_Total
0   2018        1     1.718334e+11
1   2018        2     3.043742e+11
2   2018        3     4.751015e+11
3   2018        4     6.717362e+11
4   2019        1     9.900214e+11
5   2019        2     1.354214e+12
6   2019        3     1.672559e+12
7   2019        4     2.259894e+12
8   2020        1     2.697112e+12
9   2020        2     2.646145e+12
10  2020        3     3.902053e+12
11  2020        4     5.395851e+12
12  2021        1     6.284243e+12
13  2021        2     7.476466e+12
14  2021        3     9.216696e+12
15  2021        4     1.162129e+13
16  2022        1     1.323963e+13
17  2022        2     1.550419e+13
18  2022        3     1.660763e+13
19  2022        4     1.891489e+13
20  2023        1     2.051396e+13
21  2023        2     2.291849e+13
22  2023        3     2.401213e+13
23  2023        4     2.704723e+13
24  2024        1     2.945843e+13
25  2024        2     3.182035e+13
26  2024        3     3.234697e+13
27  2024        4     3.599880e+13

In [114]:
#Query 5 — Average Transaction Value per State
#Which states have higher-value transactions?

In [115]:
query5 = """
SELECT State,
       SUM(Transaction_amount)/SUM(Transaction_count) AS Avg_Transaction_Value
FROM aggregated_transaction
GROUP BY State
ORDER BY Avg_Transaction_Value DESC;
"""

In [116]:
result5 = pd.read_sql(query5, engine)

result5

                                 State  Avg_Transaction_Value
0                              manipur            2539.397023
1                             nagaland            2380.164025
2                              mizoram            2359.883977
3                               ladakh            2261.853933
4                            meghalaya            1833.848173
5                       andhra-pradesh            1832.530061
6                          lakshadweep            1820.510982
7                               sikkim            1806.010952
8            andaman-&-nicobar-islands            1779.724994
9                    arunachal-pradesh            1712.827367
10                         west-bengal            1695.497453
11                              punjab            1683.060696
12                             tripura            1659.929700
13                               bihar            1636.167211
14                           telangana            1591.459698
15                           rajasthan            1539.771296
16                          tamil-nadu            1530.993843
17                               assam            1529.671893
18                             gujarat            1515.253438
19                       uttar-pradesh            1451.402901
20                     jammu-&-kashmir            1443.674420
21                          chandigarh            1436.835594
22                             haryana            1429.974493
23                          puducherry            1424.426946
24                                 goa            1400.271105
25                           jharkhand            1384.449911
26                              odisha            1375.112889
27                    himachal-pradesh            1372.849181
28                               delhi            1369.874807
29                      madhya-pradesh            1359.084718
30                              kerala            1336.986442
31                         uttarakhand            1313.709607
32                           karnataka            1313.447817
33                        chhattisgarh            1309.839004
34                         maharashtra            1262.277074
35  dadra-&-nagar-haveli-&-daman-&-diu            1002.492029

In [120]:
# Scenario  — User Engagement and Growth Strategy
#PhonePe seeks to enhance its market position by analyzing user engagement across different states and districts. With a significant number of registered users and app opens, understanding user behavior can provide valuable insights for strategic decision-making and growth opportunities.

In [122]:
# Query 6 — Total Registered Users by State
# Which states have the highest user base?

In [123]:
query6 = """
SELECT State,
       SUM(RegisteredUsers) AS Total_Registered_Users
FROM aggregated_user
GROUP BY State
ORDER BY Total_Registered_Users DESC;
"""

In [126]:
result6 = pd.read_sql(query6, engine)

result6

                                 State  Total_Registered_Users
0                          maharashtra            4.972825e+09
1                        uttar-pradesh            3.915666e+09
2                            karnataka            3.205101e+09
3                       andhra-pradesh            2.479563e+09
4                            rajasthan            2.372101e+09
5                            telangana            2.330985e+09
6                          west-bengal            2.267428e+09
7                           tamil-nadu            2.130315e+09
8                              gujarat            1.988044e+09
9                       madhya-pradesh            1.987287e+09
10                               bihar            1.839928e+09
11                               delhi            1.470469e+09
12                             haryana            1.340602e+09
13                              odisha            1.260387e+09
14                              kerala            8.432883e+08
15                              punjab            7.307240e+08
16                           jharkhand            7.099620e+08
17                        chhattisgarh            5.955061e+08
18                               assam            4.342955e+08
19                         uttarakhand            3.757721e+08
20                    himachal-pradesh            2.135302e+08
21                     jammu-&-kashmir            1.553467e+08
22                                 goa            7.529042e+07
23                          chandigarh            5.869127e+07
24                             tripura            5.829912e+07
25                          puducherry            4.458288e+07
26  dadra-&-nagar-haveli-&-daman-&-diu            4.286171e+07
27                             manipur            3.827042e+07
28                   arunachal-pradesh            3.086127e+07
29                            nagaland            2.440523e+07
30                           meghalaya            2.371208e+07
31                              sikkim            2.058006e+07
32                             mizoram            1.022955e+07
33                              ladakh            9.246424e+06
34           andaman-&-nicobar-islands            6.857906e+06
35                         lakshadweep            5.625180e+05

In [127]:
# Query 7 — Total App Opens by State
# Which states are most active?

In [128]:
query7 = """
SELECT State,
       SUM(AppOpens) AS Total_App_Opens
FROM aggregated_user
GROUP BY State
ORDER BY Total_App_Opens DESC;
"""

In [129]:
result7 = pd.read_sql(query7, engine)

result7

                                 State  Total_App_Opens
0                          maharashtra     1.309029e+11
1                            karnataka     1.215057e+11
2                       andhra-pradesh     1.024454e+11
3                            rajasthan     1.000934e+11
4                            telangana     9.263988e+10
5                        uttar-pradesh     7.217819e+10
6                       madhya-pradesh     7.152417e+10
7                           tamil-nadu     3.957847e+10
8                               odisha     3.853636e+10
9                                bihar     3.772257e+10
10                         west-bengal     3.413920e+10
11                             gujarat     3.283336e+10
12                             haryana     2.717189e+10
13                               delhi     2.428368e+10
14                        chhattisgarh     1.928916e+10
15                           jharkhand     1.858292e+10
16                              kerala     1.043626e+10
17                               assam     1.022154e+10
18                              punjab     9.517364e+09
19                         uttarakhand     7.395509e+09
20                    himachal-pradesh     3.776042e+09
21                     jammu-&-kashmir     2.701659e+09
22                                 goa     1.470646e+09
23                   arunachal-pradesh     1.172571e+09
24                             tripura     9.466422e+08
25                             manipur     7.414055e+08
26  dadra-&-nagar-haveli-&-daman-&-diu     7.207643e+08
27                          chandigarh     7.016118e+08
28                           meghalaya     6.841067e+08
29                          puducherry     6.827597e+08
30                            nagaland     6.776493e+08
31                              sikkim     4.678160e+08
32                             mizoram     3.530931e+08
33                              ladakh     3.179896e+08
34           andaman-&-nicobar-islands     1.610036e+08
35                         lakshadweep     4.524025e+06

In [130]:
# Query 8 - App Opens per User
# Where are users most engaged?

In [131]:
query8 = """
SELECT State,
       SUM(AppOpens) / SUM(RegisteredUsers) AS Engagement_Rate
FROM aggregated_user
GROUP BY State
ORDER BY Engagement_Rate DESC;
"""

In [132]:
result8 = pd.read_sql(query8, engine)

result8

                                 State  Engagement_Rate
0                            rajasthan          42.1961
1                       andhra-pradesh          41.3159
2                            telangana          39.7428
3                    arunachal-pradesh          37.9949
4                            karnataka          37.9101
5                       madhya-pradesh          35.9909
6                              mizoram          34.5170
7                               ladakh          34.3905
8                         chhattisgarh          32.3912
9                               odisha          30.5750
10                           meghalaya          28.8506
11                            nagaland          27.7666
12                         maharashtra          26.3237
13                           jharkhand          26.1745
14                               assam          23.5359
15           andaman-&-nicobar-islands          23.4771
16                              sikkim          22.7315
17                               bihar          20.5022
18                             haryana          20.2684
19                         uttarakhand          19.6808
20                                 goa          19.5330
21                             manipur          19.3728
22                          tamil-nadu          18.5787
23                       uttar-pradesh          18.4332
24                    himachal-pradesh          17.6839
25                     jammu-&-kashmir          17.3912
26  dadra-&-nagar-haveli-&-daman-&-diu          16.8160
27                             gujarat          16.5154
28                               delhi          16.5142
29                             tripura          16.2377
30                          puducherry          15.3144
31                         west-bengal          15.0564
32                              punjab          13.0246
33                              kerala          12.3757
34                          chandigarh          11.9543
35                         lakshadweep           8.0425

In [133]:
# Query 9 — Year-wise User Growth by State
# Which states are growing fastest?

In [134]:
query9 = """
SELECT State,
       Year,
       SUM(RegisteredUsers) AS Yearly_Users
FROM aggregated_user
GROUP BY State, Year
ORDER BY State, Year;
"""

In [135]:
result9 = pd.read_sql(query9, engine)

result9

                         State  Year  Yearly_Users
0    andaman-&-nicobar-islands  2018      478676.0
1    andaman-&-nicobar-islands  2019      992398.0
2    andaman-&-nicobar-islands  2020     1702899.0
3    andaman-&-nicobar-islands  2021     2844765.0
4    andaman-&-nicobar-islands  2022      839168.0
..                         ...   ...           ...
175                west-bengal  2018   193265622.0
176                west-bengal  2019   402495500.0
177                west-bengal  2020   608226333.0
178                west-bengal  2021   822322413.0
179                west-bengal  2022   241117657.0

[180 rows x 3 columns]

In [136]:
# Query 10 — Quarterly Growth Trend Across India
# What is the Quarterly Growth Trend ?

In [137]:
query10 = """
SELECT Year,
       Quarter,
       SUM(RegisteredUsers) AS Quarterly_Users
FROM aggregated_user
GROUP BY Year, Quarter
ORDER BY Year, Quarter;
"""

In [138]:
result10 = pd.read_sql(query10, engine)

result10

    Year  Quarter  Quarterly_Users
0   2018        1     5.156542e+08
1   2018        2     7.001281e+08
2   2018        3     8.801165e+08
3   2018        4     1.124878e+09
4   2019        1     1.357754e+09
5   2019        2     1.559884e+09
6   2019        3     1.752227e+09
7   2019        4     1.961063e+09
8   2020        1     2.173319e+09
9   2020        2     2.408952e+09
10  2020        3     2.652858e+09
11  2020        4     2.906975e+09
12  2021        1     3.134830e+09
13  2021        2     3.357828e+09
14  2021        3     3.611892e+09
15  2021        4     3.862763e+09
16  2022        1     4.102457e+09

In [139]:
# Insurance Engagement Analysis
# PhonePe aims to analyze insurance transactions across various states and districts to understand the uptake of insurance services among users. This analysis will provide insights into user behavior, market demand, and potential areas for growth in insurance offerings.

In [140]:
 # Query 11 — Total Insurance Amount by State
# Which states generate the highest insurance value?

In [141]:
query11 = """
SELECT State,
       SUM(Insurance_amount) AS Total_Insurance_Amount
FROM map_insurance
GROUP BY State
ORDER BY Total_Insurance_Amount DESC;
"""

In [144]:
result11 = pd.read_sql(query11, engine)

result11

                                 State  Total_Insurance_Amount
0                            karnataka            2.743155e+09
1                          maharashtra            2.363129e+09
2                        uttar-pradesh            1.740346e+09
3                           tamil-nadu            1.555507e+09
4                               kerala            1.313719e+09
5                            telangana            1.171060e+09
6                          west-bengal            1.052463e+09
7                            rajasthan            9.596539e+08
8                              haryana            8.309812e+08
9                                delhi            8.153652e+08
10                      andhra-pradesh            8.122230e+08
11                             gujarat            7.292334e+08
12                      madhya-pradesh            7.111535e+08
13                               bihar            6.710568e+08
14                              odisha            4.165592e+08
15                               assam            4.118310e+08
16                           jharkhand            3.486714e+08
17                              punjab            3.130858e+08
18                        chhattisgarh            2.743449e+08
19                         uttarakhand            2.007066e+08
20                     jammu-&-kashmir            1.539231e+08
21                    himachal-pradesh            1.172891e+08
22                                 goa            8.373000e+07
23                          puducherry            3.712085e+07
24                             tripura            3.374246e+07
25                          chandigarh            3.328588e+07
26                   arunachal-pradesh            2.342076e+07
27                           meghalaya            2.035736e+07
28           andaman-&-nicobar-islands            1.938679e+07
29  dadra-&-nagar-haveli-&-daman-&-diu            1.799241e+07
30                              sikkim            1.088338e+07
31                            nagaland            9.156617e+06
32                              ladakh            7.808333e+06
33                             manipur            7.150454e+06
34                             mizoram            5.462592e+06
35                         lakshadweep            6.240370e+05

In [145]:
 # Query 12 — Total Insurance Policies by State
#  Which states have highest insurance adoption?

In [146]:
query12 = """
SELECT State,
       SUM(Insurance_count) AS Total_Policies
FROM map_insurance
GROUP BY State
ORDER BY Total_Policies DESC;
"""

In [147]:
result12 = pd.read_sql(query12, engine)

result12

                                 State  Total_Policies
0                            karnataka       1957404.0
1                          maharashtra       1815539.0
2                           tamil-nadu       1215269.0
3                        uttar-pradesh       1139153.0
4                            telangana        894342.0
5                          west-bengal        839715.0
6                               kerala        824235.0
7                       andhra-pradesh        697769.0
8                                delhi        652514.0
9                            rajasthan        639684.0
10                             haryana        573738.0
11                             gujarat        562595.0
12                               bihar        536592.0
13                      madhya-pradesh        487180.0
14                              odisha        318769.0
15                               assam        262818.0
16                           jharkhand        260827.0
17                        chhattisgarh        189517.0
18                              punjab        180011.0
19                         uttarakhand        124374.0
20                     jammu-&-kashmir         78375.0
21                    himachal-pradesh         61790.0
22                                 goa         59872.0
23                          puducherry         27940.0
24                             tripura         25192.0
25                          chandigarh         22079.0
26  dadra-&-nagar-haveli-&-daman-&-diu         13792.0
27           andaman-&-nicobar-islands         12997.0
28                           meghalaya         10461.0
29                   arunachal-pradesh         10214.0
30                              sikkim          4896.0
31                            nagaland          4745.0
32                             manipur          3731.0
33                             mizoram          3724.0
34                              ladakh          3338.0
35                         lakshadweep           496.0

In [148]:
 # Query 13 — District-Level Insurance Leaders
 # Which districts drive insurance revenue?

In [149]:
query13 = """
SELECT State,
       District,
       SUM(Insurance_amount) AS Total_Amount
FROM map_insurance
GROUP BY State, District
ORDER BY Total_Amount DESC;
"""

In [150]:
result13 = pd.read_sql(query13, engine)

result13

           State                  District  Total_Amount
0      karnataka  bengaluru urban district  1.491958e+09
1    maharashtra             pune district  5.340308e+08
2    maharashtra            thane district  3.040710e+08
3      telangana       rangareddy district  2.973588e+08
4     tamil-nadu          chennai district  2.728055e+08
..           ...                       ...           ...
846     nagaland         tseminyu district  8.073000e+03
847      mizoram         khawzawl district  8.037000e+03
848     nagaland           noklak district  5.427000e+03
849      manipur         pherzawl district  9.600000e+01
850      mizoram        hnahthial district  6.200000e+01

[851 rows x 3 columns]

In [151]:
 # Query 14 — Year-wise Insurance Growth
# How is insurance growing over time?

In [152]:
query14 = """
SELECT Year,
       SUM(Insurance_amount) AS Yearly_Total_Amount
FROM map_insurance
GROUP BY Year
ORDER BY Year;
"""

In [153]:
result14 = pd.read_sql(query14, engine)

result14

   Year  Yearly_Total_Amount
0  2020         2.942072e+08
1  2021         1.499170e+09
2  2022         4.238843e+09
3  2023         6.056606e+09
4  2024         7.926752e+09

In [154]:
# Query15 - Average Insurance Value per District
# What is the Average Insurance for each district ?

In [155]:
query15 = """
SELECT State,
       District,
       SUM(Insurance_amount) / SUM(Insurance_count)
       AS Avg_Value
FROM map_insurance
GROUP BY State, District
ORDER BY Avg_Value DESC;
"""

In [156]:
result15 = pd.read_sql(query15, engine)

result15

                 State                   District    Avg_Value
0             nagaland          shamator district  5767.500000
1    arunachal-pradesh          longding district  3061.556701
2    arunachal-pradesh         lepa rada district  2959.870130
3             nagaland        mokokchung district  2894.853333
4     himachal-pradesh   lahul and spiti district  2870.864583
..                 ...                        ...          ...
846     andhra-pradesh          prakasam district  1001.287016
847          telangana  jogulamba gadwal district   980.218790
848  arunachal-pradesh         kra daadi district   929.178571
849            manipur          pherzawl district    32.000000
850            mizoram         hnahthial district    31.000000

[851 rows x 3 columns]

In [157]:
#Senario - Transaction Analysis Across States and Districts 
# PhonePe is conducting an analysis of transaction data to identify the top-performing states, districts, and pin codes in terms of transaction volume and value. This analysis will help understand user engagement patterns and identify key areas for targeted marketing efforts..
# Query 16 - District-Level Transaction 
# Which districts contribute most to total transaction value?

In [160]:
query16 = """
SELECT Entity_name AS District,
       SUM(Transaction_amount) AS Total_Value
FROM top_transaction
WHERE Level = 'District'
GROUP BY Entity_name
ORDER BY Total_Value DESC
LIMIT 7;
"""

In [161]:
result16 = pd.read_sql(query16, engine)

result16

             District   Total_Value
0     bengaluru urban  1.993784e+13
1           hyderabad  1.190694e+13
2                pune  9.730218e+12
3              jaipur  7.854092e+12
4          rangareddy  7.155140e+12
5  medchal malkajgiri  5.758878e+12
6       visakhapatnam  4.198568e+12

In [162]:
#Query 17 - Top Pincode by Transaction Count
# Which pincodes have highest transaction activity?

In [163]:
query17 = """
SELECT Entity_name AS Pincode,
       SUM(Transaction_count) AS Total_Count
FROM top_transaction
WHERE Level = 'Pincode'
GROUP BY Entity_name
ORDER BY Total_Count DESC
LIMIT 10;
"""

In [164]:
result17 = pd.read_sql(query17, engine)

result17

  Pincode   Total_Count
0  500034  1.799788e+09
1  560001  1.508571e+09
2  500001  1.473824e+09
3  110006  1.266160e+09
4  411004  1.241541e+09
5  800001  8.706976e+08
6  302016  8.564585e+08
7  411033  7.886685e+08
8  500072  7.713284e+08
9  302012  7.695529e+08

In [165]:
# Query 18 - Average Transaction Value by District
# Average Transaction Value by District ?

In [166]:
query18 = """
SELECT State,
       Entity_name AS District,
       SUM(Transaction_amount) / 
       NULLIF(SUM(Transaction_count), 0) AS Avg_Transaction_Value
FROM top_transaction
WHERE Level = 'District'
GROUP BY State, Entity_name
ORDER BY Avg_Transaction_Value DESC;
"""

In [167]:
result18 = pd.read_sql(query18, engine)

result18

               State    District  Avg_Transaction_Value
0            mizoram       saiha            3557.252262
1    jammu-&-kashmir      ramban            3504.554347
2    jammu-&-kashmir       reasi            3371.965035
3            manipur  tengnoupal            3267.609244
4           nagaland    longleng            3063.883677
..               ...         ...                    ...
409           odisha    nayagarh             589.625797
410    uttar-pradesh     sitapur             527.829086
411  jammu-&-kashmir   bandipore             523.067072
412      west-bengal     purulia             476.694876
413      west-bengal     bankura             461.910854

[414 rows x 3 columns]

In [168]:
# Query 19 - Year-wise Transaction Growth
# How are transactions growing over time?

In [169]:
query19 = """
SELECT Year,
       SUM(Transaction_amount) AS Yearly_Value
FROM top_transaction
GROUP BY Year
ORDER BY Year;
"""

In [170]:
result19 = pd.read_sql(query19, engine)

result19

   Year  Yearly_Value
0  2018  1.642045e+12
1  2019  7.259768e+12
2  2020  1.554499e+13
3  2021  3.723455e+13
4  2022  7.193910e+13
5  2023  7.634411e+13
6  2024  9.930211e+13

In [171]:
# Query 20 - District vs Pincode Comparison

In [172]:
query20 = """
SELECT Level,
       SUM(Transaction_amount) AS Total_Value
FROM top_transaction
GROUP BY Level;
"""

In [173]:
result20 = pd.read_sql(query20, engine)

result20

      Level   Total_Value
0  District  2.421446e+14
1   Pincode  6.712202e+13

In [174]:
# User Registration Analysis 
# PhonePe aims to conduct an analysis of user registration data to identify the top states, districts, and pin codes from which the most users registered during a specific year-quarter combination. This analysis will provide insights into user engagement patterns and highlight potential growth areas.
# Query 21 - State-wise Total Registrations

In [178]:
query21 = """
SELECT State,
       SUM(Registered_Users) AS Total_Registrations
FROM top_user
WHERE Level = 'District'
GROUP BY State
ORDER BY Total_Registrations DESC;
"""

In [179]:
result21 = pd.read_sql(query21, engine)

result21

                                 State  Total_Registrations
0                          maharashtra          762148724.0
1                            karnataka          512981935.0
2                       andhra-pradesh          461355136.0
3                        uttar-pradesh          384928232.0
4                            telangana          380761595.0
5                          west-bengal          372244332.0
6                            rajasthan          328838825.0
7                              gujarat          327003497.0
8                                delhi          307002677.0
9                           tamil-nadu          306477729.0
10                               bihar          219134887.0
11                      madhya-pradesh          218682209.0
12                             haryana          212890661.0
13                              odisha          183896503.0
14                              kerala          180362701.0
15                           jharkhand          130500410.0
16                              punjab          130135619.0
17                        chhattisgarh           99942806.0
18                         uttarakhand           83518089.0
19                               assam           63991416.0
20                    himachal-pradesh           49008673.0
21                     jammu-&-kashmir           30962698.0
22                                 goa           17437286.0
23                             tripura           13862627.0
24                          chandigarh           12855589.0
25                          puducherry           10407148.0
26  dadra-&-nagar-haveli-&-daman-&-diu           10080195.0
27                             manipur            8830569.0
28                   arunachal-pradesh            6592041.0
29                            nagaland            6166939.0
30                           meghalaya            6125264.0
31                              sikkim            4868004.0
32                             mizoram            2695457.0
33                              ladakh            2271369.0
34           andaman-&-nicobar-islands            1842465.0
35                         lakshadweep             142697.0

In [180]:
# Query 22 - Registration Growth Over Time (All India)

In [181]:
query22 = """
SELECT Year,
       Quarter,
       SUM(Registered_Users) AS Quarterly_Registrations
FROM top_user
GROUP BY Year, Quarter
ORDER BY Year, Quarter;
"""

In [182]:
result22 = pd.read_sql(query22, engine)

result22

    Year  Quarter  Quarterly_Registrations
0   2018        1               39790310.0
1   2018        2               53389872.0
2   2018        3               66514335.0
3   2018        4               84862265.0
4   2019        1              102056322.0
5   2019        2              116635445.0
6   2019        3              130683372.0
7   2019        4              144901350.0
8   2020        1              159060914.0
9   2020        2              174010504.0
10  2020        3              190232161.0
11  2020        4              207504211.0
12  2021        1              223408117.0
13  2021        2              238902019.0
14  2021        3              256378371.0
15  2021        4              273766810.0
16  2022        1              290251225.0
17  2022        2              305849547.0
18  2022        3              321924204.0
19  2022        4              337429011.0
20  2023        1              352745005.0
21  2023        2              366485005.0
22  2023        3              380890978.0
23  2023        4              394421001.0
24  2024        1              409995174.0
25  2024        2              425434677.0
26  2024        3              410877727.0
27  2024        4              423502943.0

In [183]:
# Query 23 - District-Level Top Performers

In [184]:
query23 = """
SELECT State,
       Entity_name AS District,
       SUM(Registered_Users) AS Total_Registrations
FROM top_user
WHERE Level = 'District'
GROUP BY State, Entity_name
ORDER BY Total_Registrations DESC
LIMIT 10;
"""

In [185]:
result23 = pd.read_sql(query23, engine)

result23

         State                    District  Total_Registrations
0    karnataka             bengaluru urban          303663088.0
1  maharashtra                        pune          199346186.0
2  maharashtra                       thane          122501643.0
3    rajasthan                      jaipur          119739290.0
4  maharashtra             mumbai suburban          119012886.0
5    telangana                   hyderabad          101824322.0
6    telangana                  rangareddy           90261099.0
7      gujarat                   ahmadabad           81767310.0
8      gujarat                       surat           77469508.0
9  west-bengal  north twenty four parganas           77396295.0

In [186]:
# Query 24 - pincode level Top Performance

In [187]:
query24 = """
SELECT Entity_name AS Pincode,
       SUM(Registered_Users) AS Total_Registrations
FROM top_user
WHERE Level = 'Pincode'
GROUP BY Entity_name
ORDER BY Total_Registrations DESC
LIMIT 10;
"""

In [188]:
result24 = pd.read_sql(query24, engine)

result24

  Pincode  Total_Registrations
0  201301           16876987.0
1  110059           14167569.0
2  560068           13002727.0
3  421302           12366260.0
4  500072           11771379.0
5  110092           11205830.0
6  122001           11127873.0
7  110086            9749619.0
8  121004            9675789.0
9  201009            9418660.0

In [189]:
# Query 25 - District Contribution Inside Each State

In [190]:
query25 = """
SELECT State,
       Entity_name AS District,
       SUM(Registered_Users) AS Total_Registrations
FROM top_user
WHERE Level = 'District'
GROUP BY State, Entity_name;
"""

In [191]:
result25 = pd.read_sql(query25, engine)

result25

                         State                  District  Total_Registrations
0    andaman-&-nicobar-islands             south andaman            1537895.0
1    andaman-&-nicobar-islands  north and middle andaman             247712.0
2    andaman-&-nicobar-islands                  nicobars              41665.0
3    andaman-&-nicobar-islands                   nicobar              15193.0
4               andhra-pradesh             visakhapatnam           69880470.0
..                         ...                       ...                  ...
348                west-bengal                    howrah           29557607.0
349                west-bengal                     nadia           27923114.0
350                west-bengal           purba medinipur           27426858.0
351                west-bengal         paschim medinipur           24820614.0
352                west-bengal           purba bardhaman           14948655.0

[353 rows x 3 columns]